- name: 拷贝kafka_exporter包
  unarchive: src=config/kafka/kafka_exporter-1.2.0.linux-amd64.tar.gz dest=/opt/
- name: 重命名
  shell: cd /opt && mv kafka_exporter-1.2.0.linux-amd64  kafka_exporter
- name: 删除压缩包
  file:
    path: /opt/kafka_exporter-1.2.0.linux-amd64.tar.gz
    state: absent
- name: 添加kafka_exporter服务
  template: 
    src: config/kafka/kafka_exporter.service
    dest: /usr/lib/systemd/system/
- name: service_reload
  shell: systemctl daemon-reload
- name: 设置开机自动启动
  shell: systemctl enable kafka_exporter.service
- name: 启动服务
  shell: systemctl start kafka_exporter.service
