- name: 拷贝elasticsearch_exporter包
  unarchive: src=config/elasticsearch/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz dest=/opt/
- name: 重命名
  shell: cd /opt && mv elasticsearch_exporter-1.1.0.linux-amd64  elasticsearch_exporter
- name: 删除压缩包
  file:
    path: /opt/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz
    state: absent
- name: 添加elasticsearch_exporter服务
  template: 
    src: config/elasticsearch/elasticsearch_exporter.service
    dest: /usr/lib/systemd/system/
- name: service_reload
  shell: systemctl daemon-reload
- name: 设置开机自动启动
  shell: systemctl enable elasticsearch_exporter.service
- name: 启动服务
  shell: systemctl start elasticsearch_exporter.service
