- name: 安装oracle_exporter
  unarchive: src=config/oracle/oracledb_exporter.0.3.0rc1-ora18.5.linux-amd64.tar.gz dest=/opt/
- name: change oracle exporter directory name
  shell: mv /opt/oracledb_exporter.0.3.0rc1-ora18.5.linux-amd64 /opt/oracle_exporter
- name: 添加oracle_exporter服务
  copy: 
    src: config/oracle/oracle_exporter.service
    dest: /usr/lib/systemd/system/
- name: delete_file
  file:
    path: /opt/oracledb_exporter.0.3.0rc1-ora18.5.linux-amd64.tar.gz
    state: absent
- name: service_reload
  shell: systemctl daemon-reload
- name: 设置开机自动启动
  shell: systemctl enable oracle_exporter.service 
- name: 启动服务
  shell: systemctl start oracle_exporter.service 
