- name: 拷贝postgres_exporter包
  unarchive: src=config/postgres/postgres_exporter-0.9.0.linux-amd64.tar.gz dest=/opt/
- name: 重命名
  shell: cd /opt && mv postgres_exporter-0.9.0.linux-amd64  postgres_exporter
- name: 删除压缩包
  file:
    path: /opt/postgres_exporter-0.9.0.linux-amd64.tar.gz
    state: absent
- name: 添加node_exporter服务
  copy: 
    src: config/postgres/postgres_exporter.service
    dest: /usr/lib/systemd/system/
- name: service_reload
  shell: systemctl daemon-reload
- name: 设置开机自动启动
  shell: systemctl enable postgres_exporter.service
- name: 启动服务
  shell: systemctl start postgres_exporter.service
